# Generated by Django 5.1.5 on 2025-01-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='creared_at',
            new_name='created_at',
        ),
    ]
