# Generated by Django 5.1.5 on 2025-01-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_uploadeddocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
    ]
