# Generated by Django 5.1.5 on 2025-01-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_delete_uploadeddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session_id',
        ),
    ]
